const userContraints={
  LOGIN_REQUEST:"USER_LOGIN_REQUEST",
  LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
  LOGIN_FAILED:"USER_LOGIN_FAILED",

  REGISTER_REQUEST:"USER_REGISTRATION_REQUEST",
  REGISTER_SUCCESS:"USER_REGISTRATION_SUCCESS",
  REGISTER_FAILED:"USER_REGISTRATION_FAILED",

  UPDATE_REQUEST:"USER_UPDATE_REQUEST",
  UPDATE_SUCCESS:"USER_UPDATE_SUCCESS",
  UPDATE_FAILED: "USER_UPDATE_FAILED",

  GET_REQUEST:"USER_LISTGET_REQUEST",
  GET_SUCCESS:"USER_LISTGET_SUCCESS",
  GET_FAILED:"USER_LISTGET_FAILED",

  DELETE_REQUEST:"USER_DELETE_REQUEST",
  DELETE_SUCCESS:"USER_DELETE_SUCCESS",
  DELETE_FAILED:"USER_DELETE_FAILED",
 
  LOGOUT:"USER_LOGOUT"
}

const alertContraints={
  SUCESS:"FETCH_SUCESS",
  ERROR:"FTECH_ERROR",
  CLEAR:"CLEAR"
}

export {userContraints,alertContraints}